---
title: "Acronym Checks"
author: "Ameek Bhalla"
date: "4/17/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs}
library(tidyverse)
library(readr)
```

```{r data}

# 330 parsing failures; incorrect number of slashes for escaping tabs
full1 <- read_delim("57593_full.txt", delim = "\t", escape_double = FALSE, col_names = FALSE)
# no parsing failures; correct number of slashes required for specifying tab as the delimiter
full1 <- read_delim("57593_full.txt", delim = "\\t", escape_double = FALSE, col_names = FALSE)

# any white space as delimiter, including tabs and space
full2 <- read_delim("57593_full.txt", delim = "\\s", escape_double = FALSE, col_names = FALSE)

# period as delimiter
full3 <- read_delim("57593_full.txt", delim = '\\.', escape_double = FALSE, col_names = FALSE)

# using table function
full4 <- read_table("57593_full.txt")

# reads in as a character vector
full5 <- read_file("57593_full.txt")

#check
(full6$`  *` == full2$`*`) %>% all()
```

```{r non_consecutive_tables}
tables <- problems(full) %>% 
  mutate(gap = row - lag(row)) 
 
tables %>% select(row) %>% slice(n = 1)

tables %>% arrange(desc(gap))
```

```{r consecutive_tables}
full$X1 %>% str_which("Table\\s\\/\\d+") %>% arrange() %>% desc()
# mutate(match = str_detect(X1, "Table/d+/")) %>% 
filter(str_detect(X1, "Table\\s\\/\\d+"))

c( tables[[1, 1]], tables %>% arrange(desc(gap)) %>% top_n(3) %>% arrange(gap) %>% pluck(1))

full$X1 %>% str_which("Table\\s\\/\\d+")
#488 & 847 are from header of the table, they will not be present usually
full$X1 %>% str_which("Table\\s\\/\\d+") %>% .[c(1,3, 5)]



#material between tabs is spliced out, a copy of the text with the correct separator will have to be read in

#capture between the first gap and next Table\\s\\/\\d+: pattern
```
